# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orchestrator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("orchestrator.proto", :syntax => :proto3) do
    add_message "orch.Orchestrator" do
      optional :name, :string, 1
      optional :status, :string, 2
    end
  end
end

module Orch
  Orchestrator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orch.Orchestrator").msgclass
end
