# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vm.proto", :syntax => :proto3) do
    add_message "vm.CreateVMRequest" do
      optional :imageName, :string, 1
    end
    add_message "vm.VM" do
      optional :id, :int64, 1
      optional :imageName, :string, 2
      optional :status, :string, 3
    end
  end
end

module Vm
  CreateVMRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vm.CreateVMRequest").msgclass
  VM = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vm.VM").msgclass
end
